# Bug report GitHub issue form
# 
# This file needs to reside in the ".github/ISSUE_TEMPLATE/" folder.

name: Bug Report
description: Submit a bug report
labels:
  - Bug
title: "Bug Report: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report to the DCC-EX team!

        In order to help us to validate the bug and ascertain what's causing it, please provide as much information as possible in this form.

  - type: input
    id: version
    attributes:
      label: EX-DCCInspector Version
      description: Please provide the version of EX-DCCInspector in use.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Please provide a clear and concise description of what the symptoms of the bug are.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce the bug
      description: Please provide the steps to reproduce the behaviour.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behaviour
      description: Please provide a clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, upload any screenshots here.

  - type: textarea
    id: hardware
    attributes:
      label: Hardware in use
      description: Please provide details of hardware in use.
      placeholder: |
        Arduino Nano
    validations:
      required: true

  - type: textarea
    id: extra-context
    attributes:
      label: Additional context
      description: Please provide any other relevant information that could help us resolve this issue, for example a customised config.h file.